import { TestBed, ComponentFixture } from '@angular/core/testing';
import { By } from '@angular/platform-browser';
import { hexToRgb, getRGBString } from '.';

fdescribe('Convert color helper', () => {
  const testRedHexColor = '#fb3a3a';
  const testRedRGBString = 'rgb(251, 58, 58)';
  const testRedRGBCollection = [251, 58, 58];
  const notValidData = 123;


  it('should convert color from hex ot rgb format', () => {
    expect(hexToRgb(testRedHexColor)).toEqual(testRedRGBCollection);
  });


  it('should return color string generated by hexToRgb function result', () => {
    expect(getRGBString(testRedRGBCollection)).toBe(testRedRGBString);
  });

  it('should throw error when type of hex data isn\'t string', () => {
    expect(() => hexToRgb(notValidData)).toThrowError('Expected a string');
  });

  it('should throw error when type of rgb collection data isn\'t Array', () => {
    expect(() => getRGBString(notValidData)).toThrowError('Expected an Array');
  });

});
